<?xml version="1.0"?>
<package format="3">
  <name>sensor_gui</name>
  <version>0.0.1</version>
  <description>Qt5 + RViz2 embedded GUI for sensor testing</description>

  <maintainer email="hyjoe@everybot.net">HwanyeongJoe</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>ament_index_cpp</depend>
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>geometry_msgs</depend>
  <depend>rviz_common</depend>
  <depend>rviz_default_plugins</depend>
  <depend>qtbase5-dev</depend>
  <depend>libgl1-mesa-dev</depend>
  <depend>freeglut3-dev</depend>
  <depend>libglu1-mesa-dev</depend>
  <depend>robot_custom_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
