teleop_velocity_smoother_node:
  ros__parameters:
    dt_sec: 0.01 # 100 Hz
    timeout_sec: 1.0
    linear:
      max_vel: 0.5
      max_accel: 0.6
      max_jerk: 2.0
    angular:
      max_vel: 0.785398
      max_accel: 2.5
      max_jerk: 8.0
