sensor_manager:
  ros__parameters:

    target_frame: "map" # "map" or "base_link"
    output_topic_prefix: "pointcloud/"

    sensors:
      tof_mono:
        use: true
        reset_timeout_sec: 30.0 # 마지막 데이터 수신 후 타임아웃으로 간주하고 내부 상태 리셋하는 기준 시간
        topic: "tof/mono"
        publish_rate_ms: 10
        extrinsics:
          translation:
            x: 0.0942
            y: 0.0
            z: 0.56513
          rotation: # deg
            roll: 0.0
            pitch: -39.0 # (-)가 들리는 방향
            yaw: 0.0

      tof_multi:
        use: true
        topic: "tof/multi"
        publish_rate_ms: 100
        enable_8x8: true # 8x8 인덱스 사용 여부
        calibration:
          method: "Max" # "Max" or "Median"
          sampling_count: 300
          pass_min_value: 0.250 # raw sensor data "이상"인 경우 통과
          pass_max_value: 0.370 # raw sensor data "이하"인 경우 통과
          pass_diff_th: 0.030   # raw data min,max의 diff 가 30mm "이하"인 경우 통과
          time_out_sec: 10.0 # 한쪽 캘리브레이션 완료 후 최대 대기시간, 실패 시 timeout fail 처리
          data_non_renewal_count: 90

      tof_multi_left:
        use: true
        reset_timeout_sec: 30.0
        topic: "tof/multi/left"
        topic_idx: "tof/multi/left/idx_"
        sub_cell_idx_array: [
          0, 3, 6,
          17, 20, 23,
          28, 31,
          44, 47,
          49, 52, 55,
          57, 60, 63
        ]
        extrinsics:
          fov: 45.0 # deg
          translation:
            x: 0.14316
            y: 0.075446
            z: 0.03
          rotation: # deg
            roll: 0.0
            pitch: -5.0 # (-)가 들리는 방향
            yaw: 15.0

      tof_multi_right:
        use: true
        reset_timeout_sec: 30.0
        topic: "tof/multi/right"
        topic_idx: "tof/multi/right/idx_"
        pitch_angle_deg: -5.0 # (-)가 들리는 방향
        sub_cell_idx_array: [
          1, 4, 7,
          16, 19, 22,
          24, 27,
          40, 43,
          48, 51, 54,
          56, 59, 62
        ]
        extrinsics:
          fov: 45.0 # deg
          translation:
            x: 0.14316
            y: -0.075446
            z: 0.03
          rotation: # deg
            roll: 0.0
            pitch: -5.0 # (-)가 들리는 방향
            yaw: -15.0

      camera:
        use: true
        reset_timeout_sec: 30.0
        topic: "camera_object"
        publish_rate_ms: 100
        pointcloud_resolution: 0.05
        class_id_confidence_th: # 형식: "class id: confidence score"
          - "0: 0"  #cable
          - "1: 0"  #carpet [Unused]
          - "2: 0"  #clothes
          - "3: 0"  #liquid [Unused]
          - "4: 0"  #non_obstacle [Unused]
          - "5: 0"  #obstacle [Unused]
          - "6: 0"  #poop
          - "7: 0"  #scale
          # - "8: 0"  #threshold [Unused]
          # - "9: 0"  #person
          - "10: 0" #dog [Unused]
          - "11: 0" #cat [Unused]
          - "12: 0" #chair
          - "13: 0" #base
          # - "14: 0" #shoes
          - "15: 0" #electronic_device
          - "16: 0" #dryingrack
          - "17: 0" #bed
          - "18: 0"
          - "19: 0"
          - "20: 0"
        object_direction: true  # 정방향(CCW+):True, 역방향(CW+):False
        object_max_distance_m: 1.5 # 최대 장애물 거리 (해당 거리 이내의 장애물 정보만 처리)
        object_ignore_pitch_th_deg: 3.0 # 객체인식 장애물 무시하는 pitch 각도 (절댓값)
        extrinsics:
          translation:
            x: 0.15473
            y: 0.0
            z: 0.5331
        logger:
          use: true
          margin:
            distance_diff: 1.0

      bottom_ir:
        use: true
        reset_timeout_sec: 30.0
        topic: "bottom_ir"
        publish_rate_ms: 10
        extrinsics:
          distance: 0.15 # distance from robot center
          angle: 50.0 # deg to next ir sensor (CW)

      collision_front:
        use: true
        reset_timeout_sec: 30.0
        topic: "collision/front"
        publish_rate_ms: 10
        extrinsics:
          distance: 0.19 # forward point offset

      collision_rear:
        use: true
        reset_timeout_sec: 30.0
        topic: "collision/rear"
        publish_rate_ms: 10
        extrinsics:
          distance: 0.19 # backward point offset

      empty:
        use: true
        reset_timeout_sec: -1.0 # 비활성화

    use_sim_time: false

################################
#######  ToF Matrix idx  #######
#                              #
#       [00, 01, 02, 03]       #
#       [04, 05, 06, 07]       #
#       [08, 09, 10, 11]       #
#       [12, 13, 14, 15]       #
#                              #
################################
#######  Camera Object  ########
######     Class ID      #######
#
#        00: 케이블
#        01: 카펫
#        02: 옷, 수건, 양말
#        03: 액체
#        04: 비장애물
#        05: 장애물
#        06: 동물 대변
#        07: 체중계
#        08: 문턱
#        09: 사람
#        10: 개
#        11: 고양이
#        12: 의자
#        13: 선풍기, 원형책상, 기둥, 전등기둥
#        14: 신발
#        15: 전자기기 (노트북, 태블릿, 스마트폰)
#        16: 건조대
#
################################
###########  Bot IR  ###########
######### < Top View > #########
#                              #
#              ff              #
#          fl      fr          #
#                              #
#          bl      br          #
#              bb              #
#                              #
################################