airbot_sensor_to_pointcloud:
  ros__parameters:

    target_frame: "base_link" # "map" or "base_link"

    tof:
      all:
        use: true
      1D:
        use: true
        publish_rate_ms: 10
        tilting_angle_deg: 39.0 # double type
      multi:
        publish_rate_ms: 50
        enable_8x8: false
        filter:
          average_window_size: 3
          lpf_alpha: 0.8
          complementary_alpha: 0.9
        left:
          use: true
          pitch_angle_deg: -0.0 # (-)가 들리는 방향
          sub_cell_idx_array: [
            1, 3, 5, 7,
            17, 19, 21, 23,
            34, 37, 42, 45,
            50, 53, 58, 61
          ]
        right:
          use: true
          pitch_angle_deg: -0.0 # (-)가 들리는 방향
          sub_cell_idx_array: [
            0, 2, 4, 6,
            16, 18, 20, 22,
            34, 37, 42, 45,
            50, 53, 58, 61
          ]
        row:
          use: true
          publish_rate_ms: 50

    camera:
      use: true
      publish_rate_ms: 100
      pointcloud_resolution: 0.05
      class_id_confidence_th: # 형식: "class id: confidence score"
        - "0: 0" #cable     #50
        - "1: 0" #carpet    #75
        - "2: 0" #clothes   #60
        # - "5: 80" #obstacle 미사용
        - "6: 0" #poop      #30
        # - "8: 80" #threshold 미사용
      object_direction: true  # 정방향(CCW+):True, 역방향(CW+):False
      object_max_distance_m: 1.5 # 최대 장애물 거리 (해당 거리 이내의 장애물 정보만 처리)
      logger:
        use: true
        margin:
          distance_diff: 0.5
          width_diff: 0.1
          height_diff: 0.1

    cliff:
      use: true
      publish_rate_ms: 10

    collision:
      use: true
      publish_rate_ms: 10

    use_sim_time: false

################################
#######  ToF Matrix idx  #######
#                              #
#       [00, 01, 02, 03]       #
#       [04, 05, 06, 07]       #
#       [08, 09, 10, 11]       #
#       [12, 13, 14, 15]       #
#                              #
################################
######  ToF Sub Cell idx  #####
#                             #
#          +-------+          #
#          | 0 | 1 |          #
#          |---|---|          #
#          | 2 | 3 |          #
#          +-------+          #
#                             #
################################
#######  Camera Object  ########
######     Class ID      #######
#                              #
#        0: cable              #
#        1: carpet             #
#        2: clothes            #
#        3: liquid             #
#        4: non_obstacle       #
#        5: obstacle           #
#        6: poop               #
#        7: scale              #
#        8: threshold          #
#        9: person             #
#        10: dog               #
#        11: cat               #
#                              #
################################
###########  Bot IR  ###########
######### < Top View > #########
#                              #
#              ff              #
#          fl      fr          #
#                              #
#          bl      br          #
#              bb              #
#                              #
################################