airbot_sensor_to_pointcloud:
  ros__parameters:
  
    target_frame: "map" # "map" or "base_link"

    ################################
    #######  ToF Matrix idx  #######
    #                              #
    #       [00, 01, 02, 03]       #
    #       [04, 05, 06, 07]       #
    #       [08, 09, 10, 11]       #
    #       [12, 13, 14, 15]       #
    ################################
    tof:
      all:
        use: true
      1D:
        use: true
        publish_rate_ms: 10
        tilting_angle_deg: 45.0 # double type
      multi:
        publish_rate_ms: 50
        left:
          use: true
        right:
          use: true
        row:
          use: true
          publish_rate_ms: 50

    ###############################
    #######  Camera Object  #######
    ######     Class ID      ######
    #                             #
    #       0: cable              #
    #       1: carpet             #
    #       2: clothes            #
    #       3: liquid             #
    #       4: non_obstacle       #
    #       5: obstacle           #
    #       6: poop               #
    #       7: scale              #
    #       8: threshold          #
    #       9: person             #
    #       10: dog               #
    #       11: cat               #
    ###############################
    camera:
      use: true
      publish_rate_ms: 100
      pointcloud_resolution: 0.05
      class_id_confidence_th: # 형식: "class id: confidence score"
        - "2: 55"
        - "5: 55"
        - "6: 55"
      object_direction: true  # 정방향(CCW+):True, 역방향(CW+):False
      logger:
        use: true
        margin:
          distance_diff: 0.5
          width_diff: 0.1
          height_diff: 0.1
    
    ####################
    #####  Bot IR  #####
    ### < Top View > ###
    #                  #
    #        ff        #
    #    fl      fr    #
    #                  #
    #    bl      br    #
    #        bb        #
    #                  #
    ####################
    cliff:
      use: true
      publish_rate_ms: 10

    use_sim_time: false
