airbot_sensor_to_pointcloud:
  ros__parameters:

    target_frame: "map" # "map" or "base_link"

    output:
      topic_prefix: "sensor_to_pointcloud/"
      tof_mono:
        use: true
        topic: "tof/mono"
        publish_rate_ms: 10
        pitch_angle_deg: -39.0 # (-)가 들리는 방향 [double type]

      tof_multi:
        use: true
        topic: "tof/multi"
        publish_rate_ms: 50
        enable_8x8: true
        filter:
          moving_average:
            use: false
            enabled_4x4_idx: [
              8, 9, 10, 11,
              12, 13, 14, 15
            ]
            window_size: 3
            max_distance_th: 0.7
          low_pass:
            use: false
            enabled_4x4_idx: [
              0, 1, 2, 3,
              4, 5, 6, 7,
              8, 9, 10, 11,
              12, 13, 14, 15
            ]
            alpha: 0.8
            # a*raw + (1-a)*estimated
          complementary:
            use: false
            enabled_4x4_idx: [
              8, 9, 10, 11,
              12, 13, 14, 15
            ]
            alpha: 0.9
            # a*lpf + (1-a)*maf

      tof_multi_left:
        use: true
        topic: "tof/multi/left/idx_"
        pitch_angle_deg: -5.0 # (-)가 들리는 방향
        sub_cell_idx_array: [
          1, 4, 7, 17,
          20, 23, 28, 31,
          44, 47, 49, 52,
          55, 57, 60, 63
        ]

      tof_multi_right:
        use: true
        topic: "tof/multi/right/idx_"
        pitch_angle_deg: -5.0 # (-)가 들리는 방향
        sub_cell_idx_array: [
          0, 3, 6, 16,
          19, 22, 24, 27,
          40, 43, 48, 51,
          54, 56, 59, 62
        ]

      camera:
        use: true
        topic: "camera_object"
        publish_rate_ms: 100
        pointcloud_resolution: 0.05
        class_id_confidence_th: # 형식: "class id: confidence score"
          - "0: 0" #cable     #50
          # - "1: 0" #carpet    #75
          - "2: 0" #clothes   #60
          - "5: 0" #obstacle 미사용
          - "6: 0" #poop      #30
          # - "8: 0" #threshold 미사용
          - "12: 0" #pole
        object_direction: true  # 정방향(CCW+):True, 역방향(CW+):False
        object_max_distance_m: 1.5 # 최대 장애물 거리 (해당 거리 이내의 장애물 정보만 처리)
        logger:
          use: true
          margin:
            distance_diff: 1.0

      cliff:
        use: true
        topic: "cliff"
        publish_rate_ms: 10

      collision:
        use: true
        topic: "collision"
        publish_rate_ms: 10

    use_sim_time: false

################################
#######  ToF Matrix idx  #######
#                              #
#       [00, 01, 02, 03]       #
#       [04, 05, 06, 07]       #
#       [08, 09, 10, 11]       #
#       [12, 13, 14, 15]       #
#                              #
################################
#######  Camera Object  ########
######     Class ID      #######
#                              #
#        0: cable              #
#        1: carpet             #
#        2: clothes            #
#        3: liquid             #
#        4: non_obstacle       #
#        5: obstacle           #
#        6: poop               #
#        7: scale              #
#        8: threshold          #
#        9: person             #
#        10: dog               #
#        11: cat               #
#        12: pole              #
#                              #
################################
###########  Bot IR  ###########
######### < Top View > #########
#                              #
#              ff              #
#          fl      fr          #
#                              #
#          bl      br          #
#              bb              #
#                              #
################################