@startuml
' 스타일 설정: 가독성을 위해 테마를 살짝 입힙니다.
skinparam Style strictuml
skinparam SequenceMessageAlignment center
skinparam DefaultFontName "Verdana"

title Robot Software (AI Node) Boot Sequence Framework

' 참여 객체 정의 (Participants)
actor "User" as User
participant "ROS 2 Launcher\n" as Launch
entity "<<Camera>>\nUART or USB" as Camera
participant "/ai_interface Node\n(Legacy UART Camera)" as Node_uart_ai
participant "/vision_detector Node\n(USB Camera)" as Node_vision_detector
participant "error_monitor Node\n" as Node_error_monitor
participant "error_manager Node\n" as Node_error_manager
participant "node_manager Node\n" as Node_node_manager

User -> Launch : **robot_bringup**
activate Launch
  == ROS 2 Node Launching (Parallel) ==
  par
    ' initialize nodes
    Launch -> Node_uart_ai : launch ai_interface (UART CAM)
    Launch -> Node_vision_detector : launch vision_detector (USB CAM)
    Launch -> Node_error_monitor : launch error_monitor
    Node_error_monitor -> Node_error_monitor : set default ai_mode (UART CAM)
    Launch -> Node_error_manager : launch error_manager

    Launch -> Node_node_manager : launch node_manager
    Node_node_manager -> Node_node_manager : monitoring required node_list\nincluding <color:blue>/ai_interface</color>, <color:blue>/vision_detector</color>

    alt open Serial == True
      Node_uart_ai -> Node_uart_ai : ebable Parsing Timer (40ms)
      loop 40ms
        alt success to connect w.cam == True
          Node_uart_ai -> Camera : parse cam data
          Node_uart_ai -> Node_error_monitor : publish topics (camera, temp, version, type)
        else
          Node_uart_ai -> Node_error_manager : Publish /error/f_code/camera <color:red>**(F09-2)**</color> 
        end
      end
    else
      Node_uart_ai -> Node_uart_ai : no retry, serial open fail.
    end

    ' New USB CAM
    loop timeout <color:red>90</color> sec
      Node_vision_detector -> Camera : try to comm w. camera
      break
        Node_vision_detector -> Node_vision_detector : <color:blue>**Success**</color> to connection Node <-> CAM
      end
    end

    alt success to connect w.cam == True
      Node_vision_detector -> Camera : parse cam data
      Node_vision_detector -> Node_error_monitor : publish topics (camera, temp, version)
      Node_vision_detector -> Node_error_monitor : publish /camera_type <color:blue>**(3)**</color>
    else
      Node_vision_detector -> Node_error_manager : Publish /error/f_code/camera <color:red>**(F09-2)**</color>
      Node_vision_detector -> Node_vision_detector : Retrying to comm w. camera\nevery <color:red>10</color> sec
    end

    ' Check Activating Nodes (Error Monitor / Node Manager)
    loop timeout <color:red>120</color> sec
      Node_error_monitor -> Node_error_monitor : Listening for version topics...
      break
        Node_error_monitor -> Node_error_monitor : subscribed <color:green>**/camera_type**</color>
      end
    end

    alt camera_type != 3 (UART CAM)
      Node_error_monitor -> Node_error_monitor : Activate <color:red>**F09-3**</color> error monitor
      ' Node_error_monitor -> Node_node_manager : publish **ai_mode** (UART)
    else (USB CAM)
      Node_error_monitor -> Node_error_monitor :Deactivate <color:red>**F09-3**</color> error monitor
      ' Node_error_monitor -> Node_node_manager : publish **ai_mode** (USB)
    end

    Node_error_monitor -> Node_error_monitor : File Writing AI version info to\n <color:blue>**"/home/airbot/app_rw/ai/mode.txt"**
  end
  Launch -> User : terminated
deactivate Launch

@enduml